---
title: "1.0 Introduction to the Stock Market Winners Project (SMW)"
author: "[Rex Macey](mailto:rex@macey.us)"
date: "October 29, 2015"
output: 
  html_document: 
    number_sections: yes
---
This blog documents a "stock market winners" research project which marries machine learning and finance. The inspiration for this project is the 1988 article ["The Anatomy of a Stock Market Winner"](http://www.cfapubs.org/doi/pdf/10.2469/faj.v44.n2.16) by Marc Reinganum published in the Financial Analysts Journal.  The goal is to improve upon it using machine learning techniques.

Many stock screens have been created based on the premise that stocks with certain characteristics should outperform.  For example, people might screen for stocks with low price-to-book ratios. Generally, people have an idea of what characteristics might lead to good future stock performance and then screen for those. The [American Assocation of Individual Investors](http://www.aaii.com/stock-screens) website has many such screens and their historical performance.  

In contrast Reinganum first identified stocks which had doubled over a 12 month period, and then searched for common characteristics among those.  He identified nine. The goal is to apply the power to today's computer along with machine learning techniques such as random forests in fashion similar to that of Reinganum. This research will consider time frames other than 12 months and will also search for stocks that are likely to perform badly ("Losers") as candidates for short sales.

